[package]
name = "oratosquilla"
version = "0.1.0"
authors = ["K <kamiyaowl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.5.1"
bitflags = "1.2.1"